const PASSWORDS_DATA = 'PASSWORDS_DATA'
const NEW_WEBSITE = 'NEW_WEBSITE';

// EMITTERS
const EMPTY_MASTER_PASSWORD = 'EMPTY_MASTER_PASSWORD';
const NEW_MASTER_PASSWORD = 'NEW_MASTER_PASSWORD';
const NEW_MASTER_PASSWORD_SAVED = 'NEW_MASTER_PASSWORD_SAVED';
const CHECK_MASTER_PASSWORD = 'CHECK_MASTER_PASSWORD';
const CHECKED_MASTER_PASSWORD = 'CHECKED_MASTER_PASSWORD';
const NEW_PASSWORD_ADDED = 'NEW_PASSWORD_ADDED';
const FAILED_TO_ADD_NEW_PASSWORD = 'FAILED_TO_ADD_NEW_PASSWORD';
const PASSWORD_DECRYPT = 'PASSWORD_DECRYPT'
const PASSWORD_DECRYPTED = 'PASSWORD_DECRYPTED';
const GENERATE_RANDOM_PASSWORD = 'GENERATE_RANDOM_PASSWORD';
const GENERATED_RANDOM_PASSWORD = 'GENERATED_RANDOM_PASSWORD'

const PASSWORDS_FILE_PATH = 'src/database/passwords.csv';
const MASTER_PASSWORD_FILE_PATH = 'src/database/master.txt'

module.exports = {
    PASSWORDS_DATA,
    NEW_WEBSITE,
    EMPTY_MASTER_PASSWORD,
    NEW_MASTER_PASSWORD,
    NEW_MASTER_PASSWORD_SAVED,
    CHECK_MASTER_PASSWORD,
    CHECKED_MASTER_PASSWORD,
    NEW_PASSWORD_ADDED,
    PASSWORDS_FILE_PATH,
    MASTER_PASSWORD_FILE_PATH,
    FAILED_TO_ADD_NEW_PASSWORD,
    PASSWORD_DECRYPTED,
    PASSWORD_DECRYPT,
    GENERATED_RANDOM_PASSWORD,
    GENERATE_RANDOM_PASSWORD
}