const PASSWORDS_DATA = 'PASSWORDS_DATA'
const NEW_WEBSITE = 'NEW_WEBSITE';
const EMPTY_MASTER_PASSWORD = 'EMPTY_MASTER_PASSWORD';
const NEW_MASTER_PASSWORD = 'NEW_MASTER_PASSWORD';
const NEW_MASTER_PASSWORD_SAVED = 'NEW_MASTER_PASSWORD_SAVED';
const CHECK_MASTER_PASSWORD = 'CHECK_MASTER_PASSWORD';
const CHECKED_MASTER_PASSWORD = 'CHECKED_MASTER_PASSWORD';

module.exports = {
    PASSWORDS_DATA,
    NEW_WEBSITE,
    EMPTY_MASTER_PASSWORD,
    NEW_MASTER_PASSWORD,
    NEW_MASTER_PASSWORD_SAVED,
    CHECK_MASTER_PASSWORD,
    CHECKED_MASTER_PASSWORD,
}