const PASSWORDS_DATA = 'PASSWORDS_DATA'
const NEW_WEBSITE = 'NEW_WEBSITE';

// EMITTERS
const EMPTY_MASTER_PASSWORD = 'EMPTY_MASTER_PASSWORD';
const NEW_MASTER_PASSWORD = 'NEW_MASTER_PASSWORD';
const NEW_MASTER_PASSWORD_SAVED = 'NEW_MASTER_PASSWORD_SAVED';
const CHECK_MASTER_PASSWORD = 'CHECK_MASTER_PASSWORD';
const CHECKED_MASTER_PASSWORD = 'CHECKED_MASTER_PASSWORD';
const NEW_PASSWORD_ADDED = 'NEW_PASSWORD_ADDED';


const PASSWORDS_FILE_PATH = 'src/database/passwords.csv';
const MASTER_PASSWORD_FILE_PATH = 'src/database/master.txt'

module.exports = {
    PASSWORDS_DATA,
    NEW_WEBSITE,
    EMPTY_MASTER_PASSWORD,
    NEW_MASTER_PASSWORD,
    NEW_MASTER_PASSWORD_SAVED,
    CHECK_MASTER_PASSWORD,
    CHECKED_MASTER_PASSWORD,
    NEW_PASSWORD_ADDED,
    PASSWORDS_FILE_PATH,
    MASTER_PASSWORD_FILE_PATH
}