export const PASSWORDS_DATA = 'PASSWORDS_DATA';
export const NEW_WEBSITE = 'NEW_WEBSITE';
export const EMPTY_MASTER_PASSWORD = 'EMPTY_MASTER_PASSWORD';
export const NEW_MASTER_PASSWORD = 'NEW_MASTER_PASSWORD';
export const CHECK_MASTER_PASSWORD = 'CHECK_MASTER_PASSWORD';
export const NEW_MASTER_PASSWORD_SAVED = 'NEW_MASTER_PASSWORD_SAVED';
export const CHECKED_MASTER_PASSWORD = 'CHECKED_MASTER_PASSWORD';
export const NEW_PASSWORD_ADDED = 'NEW_PASSWORD_ADDED';
export const PASSWORD_DECRYPT = 'PASSWORD_DECRYPT';
export const PASSWORD_DECRYPTED = 'PASSWORD_DECRYPTED';
export const GENERATED_RANDOM_PASSWORD = 'GENERATED_RANDOM_PASSWORD';
export const GENERATE_RANDOM_PASSWORD = 'GENERATE_RANDOM_PASSWORD';

export const ROUTES = {
    NEW_WEBSITE: 'new-website',
    MANAGER: 'manager'
}