export const PASSWORDS_DATA = 'PASSWORDS_DATA';
export const NEW_WEBSITE = 'NEW_WEBSITE';
export const EMPTY_MASTER_PASSWORD = 'EMPTY_MASTER_PASSWORD';
export const NEW_MASTER_PASSWORD = 'NEW_MASTER_PASSWORD';
export const CHECK_MASTER_PASSWORD = 'CHECK_MASTER_PASSWORD';
export const NEW_MASTER_PASSWORD_SAVED = 'NEW_MASTER_PASSWORD_SAVED';
export const CHECKED_MASTER_PASSWORD = 'CHECKED_MASTER_PASSWORD';